### ISSUE TITLE
directory will not be created if the outputFile contains a non-existing folder

### ISSUE THREAD

**Issue by Rickyuu** [Angular-cz/karma-json-result-reporter#1]
For example, if I set outputFile with 'temp/testResults/results.json', it will show the error 'no such file or directory'. Maybe we should create the folder and the file?

**Comment by MilanLempera** [comment]
@Rickyuu Thanks for the report, now it works.

**Comment by Rickyuu** [comment]
@MilanLempera Thanks for fixing this issue. I have tested it and it works well for me now. Can you please upgrade the released package to 0.4.3? :)

**Comment by MilanLempera** [comment]
I released it as version 0.5.0 yesterday (see https://www.npmjs.com/package/karma-json-result-reporter), but I forgot to push tags to github. Now everything is done.
