### ISSUE TITLE
Log for non-failing tests?

### ISSUE THREAD

**Issue by robsimmons** [Angular-cz/karma-json-result-reporter#6]
Log messages only seem to be included for failing tests; this may be a fundamental limitation of Karma+Jasmine, but I wanted to know if you saw any way around it.

**Comment by MilanLempera** [comment]
Hi, 
reporter process result.log every time without checking test results (https://github.com/Angular-cz/karma-json-result-reporter/blob/master/index.js#L52).
But reporters set result.log only if test fails
see:
[karma-jasmine](https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L237)
[karma-mocha](https://github.com/karma-runner/karma-mocha/blob/master/src/adapter.js#L125)

I know of no way to read "raw" data from jasmine result. Reporter gets only result from runners.

**Comment by robsimmons** [comment]
Sorry for being silent before: thanks for your helpful response! I'll look into where anything is possible upstream.

**Comment by MilanLempera** [comment]
You are welcome.
